version: '3'

services:
  db:
    # We use the predefined Postgres image
    image: 'postgres'
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pg_data
    restart: always
    container_name: NOTES_DB
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  # web:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     MIX_ENV: dev
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - .:/app
# Define the volumes
volumes:
  pgdata: